package nl.tiesnaber.knhb.knhb.controllers;

import nl.tiesnaber.knhb.knhb.model.*;
import nl.tiesnaber.knhb.knhb.services.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "*")
public class MainController {
    @Autowired // This means to get the bean called PersoonRepo
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersoonRepo persoonRepo;

    @Autowired
    private SpelerRepo spelerRepo; // Get spelerRepo Bean;

    @Autowired
    private BegeleiderRepo begeleiderRepo;

    @Autowired
    private BegeleiderRolRepo begeleiderRolRepo;

    @Autowired
    private ScheidsrechterRepo scheidsrechterRepo;

    @Autowired
    private TeamRepo teamRepo;

    @Autowired
    private WedstrijdRepo wedstrijdRepo;



    @Autowired
    private UserRepo userRepo;


    @PostMapping(path="/personen/addPersoon") // Map ONLY POST Requests
    public @ResponseBody String addNewPersoon (@RequestBody Persoon persoon) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Persoon p = persoon;
        persoonRepo.save(p);
        return "Created and saved new Persoon object";
    }

    @PostMapping(path="/spelers/addSpeler")
    public @ResponseBody Speler addNewSpeler(@RequestBody Speler speler){

        Speler sp = speler;
        Speler newPlayer = spelerRepo.save(sp);
      
        return spelerRepo.findById(newPlayer.getId()).get();
    }

    @GetMapping(path="/spelers/getAll")
    public @ResponseBody Iterable<Speler> getAllSpelers(){
        return spelerRepo.findAll();
    }

    @GetMapping(path="/personen/getAll")
    public @ResponseBody Iterable<Persoon> getAllPersonen() {
        // This returns a JSON or XML with the users

        return persoonRepo.findAll();
    }

    @GetMapping(path="/teams/getAll")
    public @ResponseBody Iterable<Team> getAllTeams(){
        return teamRepo.findAll();
    }

    @GetMapping(path="/begeleiders/getAll")
    public @ResponseBody Iterable<Begeleider> getAllBegeleiders(){
        return begeleiderRepo.findAll();
    }



    @GetMapping(path="/scheidsrechters/getAll")
    public @ResponseBody Iterable<Scheidsrechter> getAllScheidsrechters(){
        return scheidsrechterRepo.findAll();
    }

    @GetMapping(path="/users/getAll")
    public @ResponseBody Iterable<User> getAllUsers(){
        return userRepo.findAll();
    }

    @GetMapping(path="/wedstrijden/getAll")
    public @ResponseBody Iterable<Wedstrijd> getAllWedstrijden(){
        return wedstrijdRepo.findAll();
    }

    @GetMapping(path="/begeleidersrollen/getAll")
    public @ResponseBody Iterable<BegeleiderRol> getAllBegeleiderRoller(){
        return begeleiderRolRepo.findAll();
    }

    @DeleteMapping(path="/clearTable")
    public @ResponseBody String clearTable(){

        persoonRepo.deleteAll();
        return "Table Cleared";
    }


}